version: '3.7'
services:
  app:
    image: node
    restart: always
    working_dir: '/hostdir'
    volumes:
        - './:/hostdir'
    command: bash -c 'npm install && npm run build && npm start'
    environment: 
        - MODE=prod
    depends_on: 
        - db
  db:
    image: 'postgres'
    environment:
      - POSTGRES_DB=coderitter_prod
      - POSTGRES_USER=coderitter_prod
      - POSTGRES_PASSWORD=1234
networks:
  publicNet:
    external: true
